CREATE TABLE TC_LOAI_HOC_PHI (
    MA NVARCHAR2(10) CONSTRAINT TC_LOAI_HOC_PHI_PK PRIMARY KEY,
    TEN NVARCHAR2(255) NOT NULL,
    ACTIVE NUMBER(1,0) DEFAULT 1 NOT NULL,
    MAIN NUMBER(1,0)
);

ALTER TABLE SV_QT_KY_LUAT ADD ID_CVD NUMBER;

ALTER TABLE DT_LICH_EVENT ADD TIET_BAT_DAU NUMBER(2,0);

ALTER TABLE DT_LICH_EVENT ADD SO_TIET NUMBER(2,0);

ALTER TABLE TC_DINH_MUC_MON_HOC ADD LOAI_HOC_PHI NVARCHAR2(10);

ALTER TABLE TC_DINH_MUC_MON_HOC ADD TEN_MON_HOC NVARCHAR2(500);

ALTER TABLE TC_DOT_DONG_LOAI_PHI ADD LOAI_HOC_PHI NVARCHAR2(10);

ALTER TABLE TC_HOC_PHI_SUB_DETAIL ADD HOC_PHI_CHINH NUMBER(1,0);

ALTER TABLE QT_DI_NUOC_NGOAI ADD ID_VAN_BAN NUMBER;

